Weibel instability (#7)
* create blank VlasovAmpereOneSpecies directory

* migrate base_units, time_opts, domain from weak_Landau_damping.yml

* add weak_Landau_damping.yml for reference

* Migration without em_fields & kinetic

Parameters from weak_Landau_damping.yml were migrated into params_VlasovAmpereOneSpecies.py
The following parameters were fully migrated:
    - grid
    - time
    - units
    - geometry
    - mhd_equilibrium

The following parameters were partially migrated:
    - em_fields
    - kinetic

* fix syntax error of prev commit

* Migrate kinetic background and perturbation

* Migrate initial_poisson from em_fields

* fix input bug in perturbation and add editable push_eta method

* Match params file to test_verif's format, fix kinetic perturbation method

Change the kinetic format of params file to match that of test_verif_VlasovAmpereOneSpecies.py from struphy/models/tests

Split kinetic's perturbation from background, and use perturbation as init
TorusModeCos perturbation is changed to ModeCos

* rename files

rename files from VlasovAmpereOneSpecies to weak_Landau_damping

* fix methods typo and input error

fix typo in Maxwellian3D and ModesCos
fix input error in mpi_dims_mask

* compile params file and add test script

* Add question comments

* improved params file for weak Landau

* new folder structure: created top level folder VlasovAmpereOneSpecies

* delete and rename files

* add main.pproc for phase space plots

* add distribution plot in pproc_weak_Landau_damping.py

* Format binning plot

Binning plot is now shown at different time step instead of only initial and final distribution

* Add param and pproc strong_Landu_damping

* add param and pproc two_stream

* Fix initial condition of two stream

* adapt plots of strong Landau damping

* Remove perturbation plot from two stream

Remove perturbation plot and use grid format for distribution plot

* add param and pproc of bump_on

* edit bump_on instability

change initial perturbation of bump on instability. Add electric field energy progression of bump_on instability

* add analytical result to two_stream

* add analytical result to weak_Landau

* add analytical result to weak_Landau

* add analytical result to strong_Landau

* edit title of weak_Landau plot

Change title of each subplots in weak_Landau for Maxwellian and perturbation to use time in ms

* retrieve units in pproc file, use seconds as (SI) units for plotting

* replace psydac -> feectools everywhere

* change Tend for strong_Landau

* change unit of strong Landau

* change unit of two stream

* change unit of strong_Landau

* change unit for bump_on

* Clean up pproc of VlasovAmpereOneSpecies for merge

* add saving pngs for video creating to two stream test case

* Create params and pproc for weibel instability

* Update parameter of Weibel instability

update maxwellain distribution and initial distribution.
update initial magnetic field (perturbation)
update initial electric field

* Adjust parameter

Set perturbation magnetic field to be along z direction
include moments from vth

* add function to calculate field energy along each axis

Error: Result differs from built in function calculating total energy.

* Compute sim_data for weibel_instability

- Set b2_var in push_vxb propagator to None
- Compute sim_data for Tend = 5_000

* Remove unsed plots from pproc_weibel_instability

Remove Initial EM and Binning distribution plots

* Create plots for result of weibel instability

* Change "e1_v1" in pproc to "e1_v1_density"

* set value of vth3

* set loading moments

* update pproc_weibel_instability

* setup parameters for weibel instability

* Update params and pproc for Struphy 3.0.2

* use set_zero_velocity for weibel instability

* update Np = 100_000

* edit parameter file for Weibel instability

* remove initial condition

* add 9 current density plot

* Update Weibel parameter file to STRUPHY 3.0.3

* update EM-field at each time step for pproc

* update EM-energy plot for STRUPHY 3.0.3

* update binning plot for STRUPHY 3.0.3 & add df binning plot

* update curren density evolution for STRUPHY 3.0.3

* add gauss law measurement and v1v2 phaseSpace

* edit pproc file for weibel

* run with bug fix in VlasovMaxwell model

* format VlasovAmpereOneSpecies

mathces the fomat of files in VlasovAmpereOneSpecies to match that of main branch

* edit description, increase clarity of params file, remove gauss measurement

* edit comments in pproc for clarity

---------

Co-authored-by: Stefan Possanner <stefan.possanner@ipp.mpg.de>